"""empty message

Revision ID: 7865774e9b8d
Revises: b917e91ecba0
Create Date: 2024-06-23 05:11:40.408910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7865774e9b8d'
down_revision = 'b917e91ecba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qset', sa.Integer(), nullable=False),
    sa.Column('qno', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('opt1', sa.String(length=100), nullable=False),
    sa.Column('opt2', sa.String(length=100), nullable=False),
    sa.Column('opt3', sa.String(length=100), nullable=False),
    sa.Column('opt4', sa.String(length=100), nullable=False),
    sa.Column('ans', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('user_ans', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('question')
    # ### end Alembic commands ###
