"""empty message

Revision ID: 9a5a62c8aea1
Revises: 505f9b17b236
Create Date: 2024-06-27 03:10:55.792345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5a62c8aea1'
down_revision = '505f9b17b236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_custom_q', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('current_custom_q')

    # ### end Alembic commands ###
